import dotevn from "dotenv";
dotevn.config();

const FIREBASE_BUCKET_URL = process.env.ENV_FIREBASE_BUCKET_URL;
const FIREBASE_API_KEY = process.env.ENV_FIREBASE_API_KEY;
const FIREBASE_AUTH_DOMAIN = process.env.ENV_FIREBASE_AUTH_DOMAIN;
const FIREBASE_PROJECT_ID = process.env.ENV_FIREBASE_PROJECT_ID;
const FIREBASE_STORAGE_BUCKET = process.env.ENV_FIREBASE_STORAGE_BUCKET;
const FIREBASE_MESSAGING_SENDER_ID =
  process.env.ENV_FIREBASE_MESSAGING_SENDER_ID;
const FIREBASE_APP_ID = process.env.ENV_FIREBASE_APP_ID;
const FIREBASE_MEASUREMENT_ID = process.env.ENV_FIREBASE_MEASUREMENT_ID;

export default {
  FIREBASE_BUCKET_URL,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
};
